### ISSUE TITLE
Does the Package Support Checking Queue Buffer Length?

### ISSUE THREAD

**Issue by siahuat0727** [volskaya/realtime_audio.flutter#3]
Hi, thank you for sharing this package!

I am wondering if this package supports checking the length of the remaining buffer in realtime. Specifically, I want to implement the following logic and would like to know if this package is suitable for it. Thanks!
```python
while True:
    if remaining_buffer() < 100ms:
        generate another 100ms of data and push it to the queue
    else:
        wait 1ms
```

**Comment by volskaya** [comment]
It should - `RealtimeAudio` has a state stream that you can listen to, with `duration` and `durationTotal` in ms.

Some pseudocode:

```dart
final audio = RealtimeAudio(playerProgressInterval: 1);
final stateSubscription =  audio.stateStream.listen((state) {
  if (state.durationTotal - state.duration < 100) {
    // generate another 100ms of data and push it to the queue
  }
});
```

Just note that `durationTotal` is always changing as more audio is queued or if the queue reaches its end.

**Comment by siahuat0727** [comment]
Thank you for the quick response and the pseudocode! I'll give this a try. Thank you! @volskaya
